language: csharp
dist: trusty
mono: none
dotnet: 2.1.302

install:
- dotnet restore

script:
- dotnet build
- dotnet test ./Simbad.Platform.Core.Tests -c Release -f netcoreapp2.0
- dotnet test ./Simbad.Platform.Persistence.Tests -c Release -f netcoreapp2.0
- dotnet test ./Simbad.Platform.Persistence.Sqlite.Tests -c Release -f netcoreapp2.0